name: "Echo Action"
description: "A simple composite action to run an echo command"
inputs:
  message:
    description: "The message to echo"
    required: true
  sample:
    description: "asldfa"
    required: true 
runs:
  using: "composite"
  steps:
    - name: Run echo command
      shell: bash
      run: |
        echo "${{ inputs.message }}"
        echo "${{ runner.arch }}"
    # - name: Setup python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: 3.12.4
    # - name: Set the value
    #   id: step_one
    #   shell: pwsh
    #   run: |
    #     echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8
    # - name: Use the value
    #   shell: pwsh
    #   id: step_two
    #   run: |
    #     echo "${{ env.action_state }}" # This will output 'yellow'
    - name: Create ZIP name
      id: zip_name
      shell: pwsh
      run: |
        echo "zip_name=desktop-${{ inputs.sample }}-${{ runner.arch }}.zip" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Check name
      shell: pwsh
      run: "echo ${{ env.zip_name }}"
