name: "Echo Action"
description: "A simple composite action to run an echo command"
inputs:
  message:
    description: "The message to echo"
    required: true
  sample:
    description: "asldfa"
    required: true 
runs:
  using: "composite"
  steps:
    - name: Run echo command
      shell: bash
      run: |
        echo "${{ inputs.message }}"
        echo "${{ runner.arch }}"
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.4
    - name: Create ZIP name
      id: zip_name
      shell: pwsh
      run: |
        $zip_name = "desktop-${{ inputs.sample }}-${{ runner.arch }}.zip"
        echo "zip_name=$zip_name" >> $env:GITHUB_ENV 
    - name: Check name
      shell: pwsh
      run: "${{ env.zip_name }}"
