name: "MacOS Matrix Workflow"

on:
  push:
    branches:
      - main

jobs:
  echo-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2025]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: AWS
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: sample
      #     role-session-name: sample
      #     audience: sample
      #     aws-region: us-east-1
      - name: Run Echo Action
        uses: ./.github/actions/echo-action
        with:
          message: "Running on ${{ matrix.os }}"
          sample: "blabla"
